name: GetPos
main: GetPos\GetPos
author: IceCruelStuff
version: 1.5.1
api: 1.4.0

load: POSTWORLD
commands:
 getpos:
  description: Gives your current coordinates
  usage: "/getpos"
  permission: pos.command.pos
  
permissions:
 pos.command.pos:
  description: Gives your current coordinates
  default: true
